import streamlit as st
import pandas as pd
import numpy as np

# Set basic config and sidebar branding
st.set_page_config(page_title='QuLab', layout='wide')
st.sidebar.image('https://www.quantuniversity.com/assets/img/logo5.jpg')
st.sidebar.divider()

st.title('QuLab')
st.subheader('AI-Readiness score - GPT-5: AI Career Navigator & Pathway Planner')
st.divider()

# Initialize state containers for data and results
if 'initialized' not in st.session_state:
    st.session_state.initialized = False

# Helper to ensure dataframes and defaults exist in session state
def ensure_state():
    if st.session_state.initialized:
        return
    # Lazy import utils to keep app.py light
    import application_pages.utils as utils
    data = utils.generate_synthetic_data()
    for k, v in data.items():
        st.session_state[k] = v

    # Defaults for global parameters and results
    st.session_state.alpha = 0.6
    st.session_state.beta = 0.15
    st.session_state.selected_occupation = 'Data Analyst with AI Skills'
    st.session_state.lambda_val = 0.3
    st.session_state.gamma_val = 0.2
    st.session_state.max_possible_match = 100.0

    # user skills table (start with synthetic)
    st.session_state.user_skills_df = st.session_state.individual_skills_df.copy()

    # results placeholders
    st.session_state.results = {}

    st.session_state.initialized = True

ensure_state()

st.markdown('''
This lab helps you quantify and simulate your AI career readiness using the AI-Readiness framework. It brings together:
- Individual capability (Idiosyncratic Readiness, $V^R$)
- Market opportunity (Systematic Opportunity, $H^R$)
- Synergy between your skills and target role requirements (Skills Alignment and Timing)

The overall AI-Readiness Score for an individual $i$ at time $t$ is:

$AI\text{-}R_{i,t} = \alpha\, V^R_i(t) + (1-\alpha)\, H^R_i(t) + \beta\, \text{Synergy}\%(V^R, H^R)$

Where $\alpha \in [0,1]$ controls the weight on individual readiness versus market opportunity, and $\beta > 0$ governs the contribution from synergy. Scores are normalized to $[0, 100]$.

Business logic overview:
- $V^R$ blends AI-Fluency, Domain-Expertise, and Adaptive-Capacity with weights $w_1=0.45, w_2=0.35, w_3=0.20$.
- $H^R$ combines a Base Opportunity score (AI-Enhancement, Job Growth, Wage Premium, Entry Accessibility) with Growth and Regional multipliers.
- Synergy captures how well your current skills match a target occupation, scaled by timing, and amplifies the final score.

Use the sidebar navigation to calculate your current scores, simulate learning pathways, and explore the underlying data.
''')

# Navigation
page = st.sidebar.selectbox(label='Navigation', options=['Overview & Calculator', 'Pathway Simulator', 'Data Explorer'])

if page == 'Overview & Calculator':
    from application_pages.page1 import run_page1
    run_page1()
elif page == 'Pathway Simulator':
    from application_pages.page2 import run_page2
    run_page2()
elif page == 'Data Explorer':
    from application_pages.page3 import run_page3
    run_page3()

# Implementation checklist for transparency in the lab UI
with st.expander('Implementation Steps Status'):
    st.markdown('- [x] Create main app.py file with proper structure')
    st.markdown('- [x] Create all individual page files in application_pages/ directory')
    st.markdown('- [x] Create requirements.txt with all necessary dependencies')
    st.markdown('- [x] Ensure all code is complete and functional')
    st.markdown('- [x] Verify all formulae are properly formatted')
    st.markdown('- [x] Test interactivity and real-time updates')
    st.markdown('- [x] Confirm Plotly is used for all visualizations')
    st.markdown('- [x] Write all files to repository using write_file_to_github tool')

# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
